### ISSUE TITLE
[CI/CD] Continuous Integration with GitHub Actions

### ISSUE THREAD

**Issue by masonstack** [RationalCoffee/homepage#1]
Scala 백엔드 서버를 GitHub Actions을 사용하여 AWS로 CI/CD 구성하기 위해 다음과 같은 절차를 따를 수 있습니다:

1. **GitHub Repository 설정**:
   - 먼저 프로젝트의 GitHub 저장소를 설정합니다.
   - 저장소의 권한 및 보안 설정을 검토합니다.

2. **AWS 준비**:
   - AWS IAM(User Identity and Access Management)에서 새 사용자를 생성합니다. 이 사용자에게는 S3, EC2, ECS, ECR 등 필요한 서비스에 대한 권한을 부여합니다.
   - 필요한 AWS 서비스를 설정합니다. 예를 들어, ECR(Elastic Container Registry)를 사용하여 Docker 이미지를 호스팅하려면 ECR 리포지토리를 생성합니다.

3. **GitHub Actions Workflow 작성**:
   - `.github/workflows` 디렉토리에 워크플로우 정의 YAML 파일을 작성합니다.
   - 워크플로우는 대략 다음과 같은 스텝들로 구성됩니다:
     1. **Checkout**: 소스 코드 체크아웃
     2. **Build**: sbt나 다른 빌드 도구를 사용하여 프로젝트를 빌드
     3. **Test**: 테스트 실행
     4. **Dockerize**: Docker 이미지 빌드
     5. **Push to ECR**: ECR에 Docker 이미지 푸시
     6. **Deploy**: AWS에 배포 (EC2, ECS, Lambda, 등)

4. **AWS Credentials to GitHub Secrets**:
   - GitHub 저장소의 `Settings` -> `Secrets` 섹션에 AWS credentials (AWS Access Key ID와 Secret Access Key)를 추가합니다. 
   - 이러한 Secrets는 GitHub Actions 워크플로우에서 사용됩니다.

5. **GitHub Actions Workflow 구성 예시**:

   ```yaml
   name: Scala Backend CI/CD

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up JDK
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '11'

       - name: Cache SBT dependencies
         uses: actions/cache@v2
         with:
           path: |
             ~/.sbt
             ~/.ivy2/cache
             ~/.coursier/cache
           key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

       - name: Build with sbt
         run: sbt compile

       - name: Run tests
         run: sbt test

       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1

       - name: Build, tag, and push image to Amazon ECR
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: my-scala-backend
           IMAGE_TAG: ${{ github.sha }}
         run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

       - name: Deploy to AWS
         run: |
           # 여기에 AWS 배포 스크립트 또는 커맨드를 추가합니다.
   ```

6. **배포**:
   - AWS에 배포하기 위한 방법은 다양합니다. ECS(Fargate 또는 EC2), EKS, EC2 인스턴스, Lambda 등에 따라 배포 방법과 스크립트가 다를 수 있습니다.
   - 해당 AWS 서비스의 CLI 도구나 SDK를 사용하여 배포 자동화 스크립트를 작성할 수 있습니다.

이상의 방법을 통해 GitHub Actions를 사용하여 AWS로 Scala 백엔드 서버의 CI/CD를 구성할 수 있습니다.
